export const ipcChannels = {
  listPlatforms: "matrix:platforms:list",
  listPlatformAccounts: "matrix:accounts:list",
  createPlatformAccount: "matrix:accounts:create",
  openPlatformLogin: "matrix:accounts:open-login",
  openPlatformAccount: "matrix:accounts:open",
  refreshPlatformAccount: "matrix:accounts:refresh",
  refreshPlatformAccountProfile: "matrix:accounts:refresh-profile",
  removePlatformAccount: "matrix:accounts:remove",
  platformAccountsChanged: "matrix:accounts:changed",
  listPlatformContents: "matrix:platform-contents:list",
  refreshPlatformContents: "matrix:platform-contents:refresh",
  openPlatformContent: "matrix:platform-contents:open",
  selectPublishMedia: "matrix:publish:select-media",
  preparePublishDraft: "matrix:publish:prepare-draft",
  listPublications: "matrix:publications:list",
  openPublicationReview: "matrix:publications:open-review",
  openPublication: "matrix:publications:open",
  publishResultUpdate: "matrix:publish:result-update",
  checkForApplicationUpdate: "matrix:application:check-for-update",
  openApplicationUpdateDownload: "matrix:application:open-update-download",
  getLocalRuntimeStatus: "matrix:runtime:status",
  setLocalRuntimeRunning: "matrix:runtime:set-running",
  openAutomationLogDirectory: "matrix:diagnostics:open-automation-logs",
  findAutomationTrace: "matrix:diagnostics:find-automation-trace",
} as const;
