export const ipcChannels = {
  listPlatforms: "matrix:platforms:list",
  listPlatformAccounts: "matrix:accounts:list",
  createPlatformAccount: "matrix:accounts:create",
  openPlatformLogin: "matrix:accounts:open-login",
  openPlatformAccount: "matrix:accounts:open",
  refreshPlatformAccount: "matrix:accounts:refresh",
  removePlatformAccount: "matrix:accounts:remove",
  platformAccountsChanged: "matrix:accounts:changed",
  selectPublishMedia: "matrix:publish:select-media",
  preparePublishDraft: "matrix:publish:prepare-draft",
  listPublications: "matrix:publications:list",
  openPublication: "matrix:publications:open",
  publishResultUpdate: "matrix:publish:result-update",
  getLocalRuntimeStatus: "matrix:runtime:status",
  setLocalRuntimeRunning: "matrix:runtime:set-running",
} as const;
